#! /bin/bash
#SBATCH -A see200002p
#SBATCH -p GPU-shared
#SBATCH --gpus=v100-32:1
#SBATCH -J nvc10k1
#SBATCH --mail-user=kris@udel.edu
#SBATCH --mail-type=ALL
#SBATCH -o %x
#SBATCH -N 1
#SBATCH -n 4

#SBATCH -t 00:20:00

./nvc_buck 10000
